---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - react

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  es2021: true
  node: true

extends:
  - airbnb-base
  # - plugin:react/recommended

parserOptions:
  ecmaVersion: latest
# parserOptions:
#   ecmaFeatures:
#     jsx: true
#   ecmaVersion: 13
#   sourceType: module

rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
