---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - react

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  es2021: true
  node: true
  jest: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/no-unresolved: "off"
  import/extensions: "off"
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]



